In [2]:
#importing all the libraries
import pandas as pd
import numpy as np
import glob
from sklearn import datasets
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.svm import LinearSVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report,accuracy_score
from sklearn.decomposition import PCA
import cv2


In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
train_live = []
for img in glob.glob("/content/drive/My Drive/Spoof_data/Training Biometrika Live/live/*.png"): 
    print(img)
    n= cv2.imread(img) #reading the training live data
    train_live.append(n.flatten()) #flattening the data to convert into 1D vector for training

/content/drive/My Drive/Spoof_data/Training Biometrika Live/live/10_1.png
/content/drive/My Drive/Spoof_data/Training Biometrika Live/live/10_3.png
/content/drive/My Drive/Spoof_data/Training Biometrika Live/live/10_2.png
/content/drive/My Drive/Spoof_data/Training Biometrika Live/live/10_5.png
/content/drive/My Drive/Spoof_data/Training Biometrika Live/live/10_4.png
/content/drive/My Drive/Spoof_data/Training Biometrika Live/live/11_5.png
/content/drive/My Drive/Spoof_data/Training Biometrika Live/live/11_2.png
/content/drive/My Drive/Spoof_data/Training Biometrika Live/live/11_1.png
/content/drive/My Drive/Spoof_data/Training Biometrika Live/live/12_3.png
/content/drive/My Drive/Spoof_data/Training Biometrika Live/live/12_2.png
/content/drive/My Drive/Spoof_data/Training Biometrika Live/live/12_4.png
/content/drive/My Drive/Spoof_data/Training Biometrika Live/live/12_5.png
/content/drive/My Drive/Spoof_data/Training Biometrika Live/live/11_3.png
/content/drive/My Drive/Spoof_data/Tra

In [5]:
train_live

[array([ 69,  69,  69, ..., 147, 147, 147], dtype=uint8),
 array([ 71,  71,  71, ..., 152, 152, 152], dtype=uint8),
 array([ 74,  74,  74, ..., 159, 159, 159], dtype=uint8),
 array([ 76,  76,  76, ..., 139, 139, 139], dtype=uint8),
 array([ 65,  65,  65, ..., 136, 136, 136], dtype=uint8),
 array([ 67,  67,  67, ..., 150, 150, 150], dtype=uint8),
 array([ 66,  66,  66, ..., 147, 147, 147], dtype=uint8),
 array([ 60,  60,  60, ..., 137, 137, 137], dtype=uint8),
 array([ 70,  70,  70, ..., 150, 150, 150], dtype=uint8),
 array([ 76,  76,  76, ..., 159, 159, 159], dtype=uint8),
 array([ 65,  65,  65, ..., 137, 137, 137], dtype=uint8),
 array([ 66,  66,  66, ..., 141, 141, 141], dtype=uint8),
 array([ 70,  70,  70, ..., 154, 154, 154], dtype=uint8),
 array([ 66,  66,  66, ..., 140, 140, 140], dtype=uint8),
 array([ 61,  61,  61, ..., 147, 147, 147], dtype=uint8),
 array([ 62,  62,  62, ..., 145, 145, 145], dtype=uint8),
 array([ 74,  74,  74, ..., 168, 168, 168], dtype=uint8),
 array([ 69,  

In [6]:
train_spoof = []
for img in glob.glob("/content/drive/My Drive/Spoof_data/Training Biometrika Spoof/Training Biometrika Spoof/spoof/*.png"): 
    print(img)
    n= cv2.imread(img) #reading the training spoof data
    train_spoof.append(n.flatten()) #flattening the data to convert into 1D vector for training


/content/drive/My Drive/Spoof_data/Training Biometrika Spoof/Training Biometrika Spoof/spoof/10_3.png
/content/drive/My Drive/Spoof_data/Training Biometrika Spoof/Training Biometrika Spoof/spoof/10_1.png
/content/drive/My Drive/Spoof_data/Training Biometrika Spoof/Training Biometrika Spoof/spoof/10_4.png
/content/drive/My Drive/Spoof_data/Training Biometrika Spoof/Training Biometrika Spoof/spoof/10_2.png
/content/drive/My Drive/Spoof_data/Training Biometrika Spoof/Training Biometrika Spoof/spoof/10_10.png
/content/drive/My Drive/Spoof_data/Training Biometrika Spoof/Training Biometrika Spoof/spoof/10_5.png
/content/drive/My Drive/Spoof_data/Training Biometrika Spoof/Training Biometrika Spoof/spoof/10_6.png
/content/drive/My Drive/Spoof_data/Training Biometrika Spoof/Training Biometrika Spoof/spoof/10_7.png
/content/drive/My Drive/Spoof_data/Training Biometrika Spoof/Training Biometrika Spoof/spoof/10_9.png
/content/drive/My Drive/Spoof_data/Training Biometrika Spoof/Training Biometrika 

In [7]:
train_spoof

[array([ 71,  71,  71, ..., 156, 156, 156], dtype=uint8),
 array([ 69,  69,  69, ..., 162, 162, 162], dtype=uint8),
 array([ 69,  69,  69, ..., 152, 152, 152], dtype=uint8),
 array([ 71,  71,  71, ..., 161, 161, 161], dtype=uint8),
 array([ 69,  69,  69, ..., 157, 157, 157], dtype=uint8),
 array([ 67,  67,  67, ..., 154, 154, 154], dtype=uint8),
 array([ 71,  71,  71, ..., 159, 159, 159], dtype=uint8),
 array([ 68,  68,  68, ..., 156, 156, 156], dtype=uint8),
 array([ 66,  66,  66, ..., 155, 155, 155], dtype=uint8),
 array([ 70,  70,  70, ..., 155, 155, 155], dtype=uint8),
 array([ 68,  68,  68, ..., 154, 154, 154], dtype=uint8),
 array([ 63,  63,  63, ..., 147, 147, 147], dtype=uint8),
 array([ 65,  65,  65, ..., 154, 154, 154], dtype=uint8),
 array([ 68,  68,  68, ..., 156, 156, 156], dtype=uint8),
 array([ 67,  67,  67, ..., 153, 153, 153], dtype=uint8),
 array([ 69,  69,  69, ..., 152, 152, 152], dtype=uint8),
 array([ 67,  67,  67, ..., 156, 156, 156], dtype=uint8),
 array([ 65,  

In [8]:
test_live = []
for img in glob.glob("/content/drive/My Drive/Spoof_data/Testing Biometrika Live/live/*.png"):
    print(img)
    n= cv2.imread(img) #reading the testing live data
    test_live.append(n.flatten()) #flattening the data to convert into 1D vector for testing

/content/drive/My Drive/Spoof_data/Testing Biometrika Live/live/11_5.png
/content/drive/My Drive/Spoof_data/Testing Biometrika Live/live/10_3.png
/content/drive/My Drive/Spoof_data/Testing Biometrika Live/live/10_5.png
/content/drive/My Drive/Spoof_data/Testing Biometrika Live/live/11_2.png
/content/drive/My Drive/Spoof_data/Testing Biometrika Live/live/11_1.png
/content/drive/My Drive/Spoof_data/Testing Biometrika Live/live/11_4.png
/content/drive/My Drive/Spoof_data/Testing Biometrika Live/live/10_1.png
/content/drive/My Drive/Spoof_data/Testing Biometrika Live/live/10_4.png
/content/drive/My Drive/Spoof_data/Testing Biometrika Live/live/10_2.png
/content/drive/My Drive/Spoof_data/Testing Biometrika Live/live/11_3.png
/content/drive/My Drive/Spoof_data/Testing Biometrika Live/live/13_2.png
/content/drive/My Drive/Spoof_data/Testing Biometrika Live/live/12_1.png
/content/drive/My Drive/Spoof_data/Testing Biometrika Live/live/13_3.png
/content/drive/My Drive/Spoof_data/Testing Biometri

In [9]:
test_live

[array([ 63,  63,  63, ..., 143, 143, 143], dtype=uint8),
 array([ 72,  72,  72, ..., 160, 160, 160], dtype=uint8),
 array([ 67,  67,  67, ..., 152, 152, 152], dtype=uint8),
 array([ 65,  65,  65, ..., 143, 143, 143], dtype=uint8),
 array([ 65,  65,  65, ..., 117, 117, 117], dtype=uint8),
 array([ 64,  64,  64, ..., 134, 134, 134], dtype=uint8),
 array([ 70,  70,  70, ..., 142, 142, 142], dtype=uint8),
 array([ 66,  66,  66, ..., 137, 137, 137], dtype=uint8),
 array([ 77,  77,  77, ..., 168, 168, 168], dtype=uint8),
 array([ 68,  68,  68, ..., 141, 141, 141], dtype=uint8),
 array([ 70,  70,  70, ..., 145, 145, 145], dtype=uint8),
 array([ 64,  64,  64, ..., 129, 129, 129], dtype=uint8),
 array([ 67,  67,  67, ..., 143, 143, 143], dtype=uint8),
 array([ 63,  63,  63, ..., 121, 121, 121], dtype=uint8),
 array([ 64,  64,  64, ..., 140, 140, 140], dtype=uint8),
 array([ 62,  62,  62, ..., 127, 127, 127], dtype=uint8),
 array([ 66,  66,  66, ..., 135, 135, 135], dtype=uint8),
 array([ 82,  

In [10]:
test_spoof = []
for img in glob.glob("/content/drive/My Drive/Spoof_data/Testing Biometrika Spoof/Testing Biometrika Spoof/spoof/*.png"):
    print(img)
    n= cv2.imread(img) #reading the testing spoof data
    test_spoof.append(n.flatten()) #flattening the data to convert into 1D vector for testing

/content/drive/My Drive/Spoof_data/Testing Biometrika Spoof/Testing Biometrika Spoof/spoof/100_3.png
/content/drive/My Drive/Spoof_data/Testing Biometrika Spoof/Testing Biometrika Spoof/spoof/100_1.png
/content/drive/My Drive/Spoof_data/Testing Biometrika Spoof/Testing Biometrika Spoof/spoof/100_5.png
/content/drive/My Drive/Spoof_data/Testing Biometrika Spoof/Testing Biometrika Spoof/spoof/100_10.png
/content/drive/My Drive/Spoof_data/Testing Biometrika Spoof/Testing Biometrika Spoof/spoof/100_8.png
/content/drive/My Drive/Spoof_data/Testing Biometrika Spoof/Testing Biometrika Spoof/spoof/100_4.png
/content/drive/My Drive/Spoof_data/Testing Biometrika Spoof/Testing Biometrika Spoof/spoof/100_6.png
/content/drive/My Drive/Spoof_data/Testing Biometrika Spoof/Testing Biometrika Spoof/spoof/122_1.png
/content/drive/My Drive/Spoof_data/Testing Biometrika Spoof/Testing Biometrika Spoof/spoof/100_7.png
/content/drive/My Drive/Spoof_data/Testing Biometrika Spoof/Testing Biometrika Spoof/spoof

In [11]:
test_spoof

[array([ 69,  69,  69, ..., 141, 141, 141], dtype=uint8),
 array([ 67,  67,  67, ..., 139, 139, 139], dtype=uint8),
 array([ 69,  69,  69, ..., 139, 139, 139], dtype=uint8),
 array([ 69,  69,  69, ..., 145, 145, 145], dtype=uint8),
 array([ 68,  68,  68, ..., 142, 142, 142], dtype=uint8),
 array([ 70,  70,  70, ..., 142, 142, 142], dtype=uint8),
 array([ 71,  71,  71, ..., 139, 139, 139], dtype=uint8),
 array([ 69,  69,  69, ..., 151, 151, 151], dtype=uint8),
 array([ 68,  68,  68, ..., 141, 141, 141], dtype=uint8),
 array([ 68,  68,  68, ..., 142, 142, 142], dtype=uint8),
 array([ 68,  68,  68, ..., 141, 141, 141], dtype=uint8),
 array([ 70,  70,  70, ..., 152, 152, 152], dtype=uint8),
 array([ 72,  72,  72, ..., 154, 154, 154], dtype=uint8),
 array([ 70,  70,  70, ..., 148, 148, 148], dtype=uint8),
 array([ 69,  69,  69, ..., 150, 150, 150], dtype=uint8),
 array([ 69,  69,  69, ..., 150, 150, 150], dtype=uint8),
 array([ 70,  70,  70, ..., 147, 147, 147], dtype=uint8),
 array([ 68,  

In [24]:
finger_print_X = []
c=0
for image in  train_spoof:
  finger_print_X.append(image) 
  c+=1
print(c)  
finger_print_X = finger_print_X[1:155] #slicing image at 155th position 
for image in train_live:
  finger_print_X.append(image) #append the image into the array 
  

207


In [25]:
finger_print_Y = []
for image in train_spoof:
  finger_print_Y.append('spoof')
finger_print_Y = finger_print_Y[1:155] #slicing images
for image in train_live:
  finger_print_Y.append('live') #append the image into the array

In [14]:
X_train = np.array(finger_print_X) 
Y_train = np.array(finger_print_Y)

In [20]:
finger_print_X = []
for image in test_live:
  finger_print_X.append(image)
for image in  test_spoof:
  finger_print_X.append(image)

In [21]:
finger_print_Y = []
for image in test_live:
  finger_print_Y.append('live')
for image in test_spoof:
  finger_print_Y.append('spoof')

In [22]:
X_test = np.array(finger_print_X)
Y_test = np.array(finger_print_Y)

In [23]:
linear = svm.SVC(kernel='linear', C=1, decision_function_shape='ovo').fit(X_train, Y_train)

In [19]:
Y_pred=linear.predict(X_test)

In [26]:
print("FingerPrint Spoof Detection Parameters")
print("Overall Accuracy using Linear SVM: "+str(accuracy_score(Y_test, Y_pred)))
#print('\n')
print(classification_report(Y_test, Y_pred))
cm = confusion_matrix(Y_test, Y_pred)
print("Accuracy for each class")
print(cm.diagonal()/cm.sum(axis=1))

FingerPrint Spoof Detection Parameters
Overall Accuracy using Linear SVM: 0.815
              precision    recall  f1-score   support

        live       0.79      0.85      0.82       200
       spoof       0.84      0.78      0.81       200

    accuracy                           0.81       400
   macro avg       0.82      0.81      0.81       400
weighted avg       0.82      0.81      0.81       400

Accuracy for each class
[0.85 0.78]
